services:
  backendapi:
    build:
      context: ./BackendAPI
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    build:
      context: ./Mongodb
    ports:
      - "27017:27017"
