version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/redbook
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2
      - ./maven-logs:/home/app/maven-logs
      - ./maven-reports:/home/app/maven-reports

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: redbook
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
networks:
  springapimysql-net: